backend:
  name: git-gateway
  branch: master
  # Change branch when pushing live

media_folder: static/img
public_folder: /img

# create collections
collections:
  - name: blog
    label: blog post
    folder: /src/cms-pages
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Foto, widget: image }
